name: 📱 Mobile Smoke Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      run_android:
        description: 'Run Android Tests'
        type: boolean
        default: true
      run_ios:
        description: 'Run iOS Tests'
        type: boolean
        default: true

jobs:
  android-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_android
    concurrency: mobile-device-resource # shared resource
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run Android UI tests
        run: |
          echo "Running Android Smoke Tests"

  ios-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_ios
    concurrency: mobile-device-resource # same shared resource
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run iOS UI tests
        run: |
          echo "Running iOS Smoke Tests"
