# .github/workflows/mobile-smoke-tests.yml
name: 📱 Mobile Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
    inputs:
      run_ios:
        description: 'Run iOS Tests'
        type: boolean
        default: true
      run_android:
        description: 'Run Android Tests'
        type: boolean
        default: true

jobs:
  ios-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_ios
    concurrency:
      group: mobile-device-${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run iOS Smoke Tests
        run: echo "🖥️ iOS tests running…"

  android-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_android
    concurrency:
      group: mobile-device-${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run Android Smoke Tests
        run: echo "🤖 Android tests running…"
