name: 📱 Mobile Smoke Tests

on:
  push:

  workflow_dispatch:
    inputs:
      run_android:
        description: 'Run Android Tests'
        type: boolean
        default: false
      run_ios:
        description: 'Run iOS Tests'
        type: boolean
        default: false

concurrency:
  group: mobile-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  android-tests:
    # Always run Android on PRs, or if manually selected
    if: github.event_name == 'pull_request' || inputs.run_android
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run Android UI tests
        run: |
          echo "Running Android Smoke Tests"

  ios-tests:
    # Run on PRs after Android completes, or if manually selected alone
    if: github.event_name == 'pull_request' || inputs.run_ios
    needs: ${{ (github.event_name == 'pull_request' && 'android-tests') || '' }}
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run iOS UI tests
        run: |
          echo "Running iOS Smoke Tests"
