name: Mobile Device Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      skip_android:
        description: "Skip Android tests?"
        required: false
        default: 'false'

jobs:
  android-tests:
    if: github.event_name == 'pull_request' && inputs.skip_android != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running Android…"

  ios-tests:
    needs: android-tests
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.skip_android == 'true')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running iOS…"
