name: 📱 Mobile Smoke Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      run_android:
        description: 'Run Android Tests'
        type: boolean
        default: true
      run_ios:
        description: 'Run iOS Tests'
        type: boolean
        default: true

concurrency:
  group: mobile-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  android-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_android
    runs-on: ubuntu-latest              # ← use GitHub-hosted, not Lambdatest
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run Android Smoke Tests
        run: |
          echo "Running Android Smoke Tests on ubuntu-latest"

  ios-tests:
    needs: android-tests
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      inputs.run_ios
    runs-on: [self-hosted, lambdatest]  # ← only iOS hits your Lambdatest pool
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run iOS Smoke Tests
        run: |
          echo "Running iOS Smoke Tests on Lambdatest"
