name: 📱 Mobile Smoke Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:
    inputs:
      run_android:
        description: 'Run Android Tests'
        type: boolean
        default: false
      run_ios:
        description: 'Run iOS Tests'
        type: boolean
        default: false

concurrency:
  group: mobile-tests-${{ github.ref }}
  cancel-in-progress: false

jobs:
  android-tests:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || inputs.run_android
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run Android UI tests
        run: |
          echo "Running Android Smoke Tests"

  ios-tests:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || inputs.run_ios
    # require Android only when this was auto-triggered (PR or push)
    needs: ${{ github.event_name != 'workflow_dispatch' && 'android-tests' || '' }}
    runs-on: [self-hosted, lambdatest]
    steps:
      - uses: actions/checkout@v4
      - name: ▶️ Run iOS UI tests
        run: |
          echo "Running iOS Smoke Tests"
